### ISSUE TITLE
Specifications of reference files

### ISSUE THREAD

**Issue by xexpanderx** [J35P312/FindSV#3]
Hi!

During installation and setup with:

`./setup.sh`

I have some problem to understand what you mean with the question:

`add the path of the directory containing reference files (i.e the directory should contain one fasta file per contig)`

I specified the reference genome for homo sapiens which is downloaded by vep:
`~/.vep/homo_sapiens/98_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz`
on the question:
`Set the path to the reference genome(needs to be indexed using bwa and samtools 0.19)`

How do I find "reference files with one fasta file per contig"? Should I split the reference genome specified by chromosome?

Thanks!

**Comment by J35P312** [comment]
Hello there!
That is correct, you need to create one separate fasta file per chromosome, and put those fasta files into a folder.
I usually download such fasta files from here:

ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/

for instance, you will find this one for chromosome 1:

ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.chromosome.1.fa.gz

But you may also write a script to split your genome fasta per chromosome.
The files needs to be unziped, otherwise, CNVNator will not be able to read them. 

you must also rename the files so that the file name of the fasta file match the chromosome names of the header, for instance

mv Homo_sapiens.GRCh37.dna.chromosome.1.fa 1.fa

If you just want to test FindSV, you may also provide an empty folder as a "reference directory", but then CNVnator will not perform GC correction.

Good luck! And tell me if you run into any problems!
//Jesper

**Comment by xexpanderx** [comment]
Thank you!

Gonna try this out.
